### ISSUE TITLE
Some extra required KDE packages

### ISSUE THREAD

**Issue by yehonatan2020** [mfgbhatti/ArchTitus#3]
Please add these extra pacman packages to make KDE more complete...

dvd+rw-tools
exfatprogs (instead of exfat-utils)
karchive
kauth
kcompletion
kdialog
kgamma5
khotkeys
kwalletmanager
kwayland-integration
kwrited

**Comment by mfgbhatti** [comment]
Hey @[yehonatan2020](https://github.com/yehonatan2020)
I am going to close it as it is. KDE packages and default installation is maintained by Chris Titus, not me.
If you want some packages you certainly asked on main branch
Thank you,
