### ISSUE TITLE
Disk Choice problem

### ISSUE THREAD

**Issue by yehonatan2020** [mfgbhatti/ArchTitus#6]
When it asks you to choose your disk for installation, there is only a number next to the top choice, but the other disks dont have a number next to it, so cant be selected

**Comment by mfgbhatti** [comment]
hey there, I cannot reproduce this bug or issue kindly give me log or snapshot of the issue to track it down.

**Comment by vladsendrix** [comment]
It also happens here!

**Comment by vladsendrix** [comment]
![Screenshot_20220221-213527_Photos](https://user-images.githubusercontent.com/83285656/155016798-7cb036d4-0cf3-4984-83fb-338c9d004476.png)

**Comment by yehonatan2020** [comment]
yep, thats the same error that i was getting.

**Comment by mfgbhatti** [comment]
it was not a array. so converted it to be an array. which will solve this issue. thank you guys
