### ISSUE TITLE
still doesnt boot

### ISSUE THREAD

**Issue by yehonatan2020** [mfgbhatti/ArchTitus#7]
Still does not boot.

**Comment by mfgbhatti** [comment]
hey there,
i need more information on this subject like which options you are selecting if any log.

**Comment by yehonatan2020** [comment]
i chose default install, but let me try again and I'll see what happens. I boot it in EFI mode btw

**Comment by yehonatan2020** [comment]
YAY! Just did a full reinstall, and got it to boot!!
